### PR TITLE
Add a 'titlecase' executable that capitalizes its command-line arguments.

### PR DESCRIPTION
**Pull request by peti**
```
$ cabal -v0 run titlecase -- titlecase is a useful shell utility to have
Titlecase Is a Useful Shell Utility to Have
```

### CODE REVIEW

**Comment by peti** [comment]
Ping?

**Comment by nkaretnikov** [comment]
@peti Pong. I'm extremely busy these days, but I'll try to resolve all the issues ASAP. I wanted to do it 7 days ago but didn't find the time.

**Comment by nkaretnikov** [comment]
@peti I've just tested it and pushed to master. I'd like to clean up some things before releasing a new version, so feel free to poke me if I forget or something. Thanks!

**Comment by nkaretnikov** [comment]
@peti Just released a new version.

**Pull request merged**
